# Generated by Django 5.1.4 on 2025-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transtype',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
